default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails_user
  password: 2469
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: traffic_development

test:
  <<: *default
  database: traffic_test

production:
  <<: *default
  database: traffic_production
